# Generated by Django 5.2.3 on 2025-07-26 18:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ogrenci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100)),
                ('kayit_tarihi', models.DateField(default=django.utils.timezone.now)),
                ('seviye', models.CharField(choices=[('A1', 'A1 - Başlangıç'), ('A2', 'A2 - Temel'), ('B1', 'B1 - Orta'), ('B2', 'B2 - İleri'), ('C1', 'C1 - Üst'), ('C2', 'C2 - Uzman')], default='A1', max_length=3)),
                ('profil_foto', models.ImageField(blank=True, null=True, upload_to='ogrenci_profil/')),
                ('ozel_notlar', models.TextField(blank=True, help_text='Öğretmen için özel notlar')),
                ('ai_notlar', models.TextField(blank=True, help_text='Yapay zeka önerileri')),
                ('son_guncelleme', models.DateField(auto_now=True)),
                ('mevcut_cuz', models.PositiveSmallIntegerField(default=1)),
                ('hedef_cuz', models.PositiveSmallIntegerField(default=30)),
                ('puan', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5)),
            ],
        ),
        migrations.CreateModel(
            name='EzberKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(default=django.utils.timezone.now)),
                ('baslangic_sayfa', models.PositiveSmallIntegerField()),
                ('bitis_sayfa', models.PositiveSmallIntegerField()),
                ('ezber_suresi', models.PositiveSmallIntegerField(help_text='Dakika cinsinden')),
                ('ogretmen_notu', models.TextField(blank=True)),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ezberler', to='mainproject.ogrenci')),
            ],
        ),
    ]
