# Generated by Django 5.2.3 on 2025-06-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_yazi_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='yazi',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
