# Generated by Django 5.2.3 on 2025-06-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_yazi_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazi',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
