# Generated by Django 5.2.3 on 2025-07-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_yazi_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazi',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
