# Generated by Django 5.2.3 on 2025-07-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_yazi_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazi',
            name='imageUrl',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
