# Generated by Django 5.2.3 on 2025-07-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_sitecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazi',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
