# Generated by Django 5.2.3 on 2025-07-26 21:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_yazi_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='yazi',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
